export default {
	addToList: true,
	chatHide: true,
	jumpUnreadMessages: true,
	favShowOnlyUnread: true,
	favShowOnlyUnreadRemember: false,
	favShowOnlyUnreadRememberOpened: false,
	shortCommentMarker: true,
	highlightForumCategories: false,
	threadedComments: false,
	blockList: '',
	autoloadNextPage: true,
	overlayReplyTo: false,
	highlightCommentsForMe: true,
	showNavigationButtons: true,
	showNavigationButtonsNight: false,
	navigationButtonsPosition: 'leftcenter',
	navigationButtonNightState: false,
	removeAds: false,
	fetchNewComments: true,
	disablePointSystem: false,
	profiles: '',
	columnifyComments: false,
	quickUserInfo: false,
	quickInsertion: false,
	msgPerPage: 80,
	inlineImageViewer: false
}