export const defaultValues = {
	chatHide: true,
/*	customBlocks: false,
	jumpUnreadedMessages: true,
	favShowOnlyUnreaded: true,
	favShowOnlyUnreadedRemember: false,
	favShowOnlyUnreadedRememberOpened: false,
	shortCommentMarker: true,
	highlightForumCategories: false,
	threadedComments: false,
	blockList: '',
	autoloadNextPage: true,
	overlayReplyTo: false,
	highlightCommentsForMe: true,
	blocksConfig: '',
	hideBlocksButtons: false,
	showNavigationButtons: true,
	showNavigationButtonsNight: false,
	navigationButtonsPosition: 'leftcenter',
	navigationButtonNightState: false,
	removeAds: false,
	topicWhitelist: '',
	fetchNewComments: true,
	disablePointSystem: false,
	profiles: '',
	debuggerMessages: '',
	columnifyComments: false,
	quickUserInfo: false,
	quickInsertion: false,
	msgPerPage: 80,
	inlineImageViewer: false*/
};